language: python
python:
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install coverage
script: coverage run -m unittest discover tests # run tests
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
