language: python
python:
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements.txt
script: python -m unittest discover tests # run tests
after_success:
  - $ProgressPreference = 'SilentlyContinue'
  - Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
  - .\codecov.exe
